In [1]:
%reset -f

In [2]:
import pandas as pd
#import vaex
import os
from runner import runner

In [3]:
outputDir = '../../nlp/data/output/'
outFile = 'broadMediumLocal.tsv'
inputDir = '../../nlp/data/input/'
targetDir = '../../target/'
inFile = 'harmonized-table.parquet.gz'
settingsFile = '../../nlp/settings.ini'
termlistFolder = '../../nlp/terms'
cols = ['id', 'accession_biosample_id','env_broad_scale','env_medium','package_name','env_local_scale']

In [4]:
%%time
harmonizedDF = pd.read_parquet(os.path.join(targetDir, inFile))
harmonizedDF.head()

CPU times: user 3min 58s, sys: 1min 31s, total: 5min 29s
Wall time: 3min 18s

,id,slope_gradient,stud_book_number,sample_type,magnesium,host_sex,ref_biomaterial,host_subject_id,humidity,bromide,...,analyte_type,title,light_intensity,carb_nitro_ratio,turbidity,silicate,previous_land_use_meth,indoor_space,org_nitro,infra_specific_name
0,BIOSAMPLE:SAMN00000002,None,None,None,None,None,not determined,None,None,None,...,None,Alistipes putredinis DSM 17216,None,None,None,None,None,None,None,None
1,BIOSAMPLE:SAMN00000003,None,None,None,None,None,not determined,None,None,None,...,None,Anaerotruncus colihominis DSM 17241,None,None,None,None,None,None,None,None
2,BIOSAMPLE:SAMN00000004,None,None,None,None,None,not determined,None,None,None,...,None,MIGS Cultured Bacterial/Archaeal sample from B...,None,None,None,None,None,None,None,None
3,BIOSAMPLE:SAMN00000005,None,None,None,None,None,None,None,None,None,...,None,Generic sample from Biomphalaria glabrata,None,None,None,None,None,None,None,None
4,BIOSAMPLE:SAMN00000006,None,None,None,None,None,None,None,None,None,...,None,Generic sample from Callithrix jacchus,None,None,None,None,None,None,None,None

In [5]:
subsetHarmonizedDF = harmonizedDF[cols]
subsetHarmonizedDF = subsetHarmonizedDF[~subsetHarmonizedDF['env_broad_scale'].isnull()]

In [6]:
subsetHarmonizedDF.head()

,id,accession_biosample_id,env_broad_scale,env_medium,package_name,env_local_scale
0,BIOSAMPLE:SAMN00000002,2,terrestrial biome [ENVO:00000446],biological product [ENVO:02000043],MIGS: cultured bacteria/archaea; version 5.0,human-associated habitat [ENVO:00009003]
1,BIOSAMPLE:SAMN00000003,3,terrestrial biome [ENVO:00000446],biological product [ENVO:02000043],MIGS: cultured bacteria/archaea; version 5.0,human-associated habitat [ENVO:00009003]
2,BIOSAMPLE:SAMN00000004,4,terrestrial biome [ENVO:00000446],biological product [ENVO:02000043],MIGS: cultured bacteria/archaea; version 5.0,human-associated habitat [ENVO:00009003]
5,BIOSAMPLE:SAMN00000007,7,terrestrial biome [ENVO:00000446],biological product [ENVO:02000043],MIGS: cultured bacteria/archaea; version 5.0,human-associated habitat [ENVO:00009003]
6,BIOSAMPLE:SAMN00000008,8,terrestrial biome [ENVO:00000446],biological product [ENVO:02000043],MIGS: cultured bacteria/archaea; version 5.0,human-associated habitat [ENVO:00009003]

In [7]:
subsetNonEnvo = subsetHarmonizedDF[~subsetHarmonizedDF['env_broad_scale'].str.contains('ENVO:\d')]
subsetNonEnvo.head()

,id,accession_biosample_id,env_broad_scale,env_medium,package_name,env_local_scale
1234,BIOSAMPLE:SAMN00001340,1340,aquatic,saline water,"MIMS: metagenome/environmental, water; version...",Pacific Ocean
1256,BIOSAMPLE:SAMN00001362,1362,aquatic,saline water,"MIMS: metagenome/environmental, water; version...",Pacific Ocean
20780,BIOSAMPLE:SAMN00027429,27429,ENVO:feces,None,Generic,ENVO:feces
20781,BIOSAMPLE:SAMN00027430,27430,ENVO:feces,None,Generic,ENVO:feces
20782,BIOSAMPLE:SAMN00027431,27431,ENVO:feces,None,Generic,ENVO:feces

In [8]:
broad_scale = list(subsetNonEnvo['env_broad_scale'].unique())

In [9]:
medium = list(subsetNonEnvo['env_medium'].unique())

In [10]:
local = list(subsetNonEnvo['env_local_scale'].unique())

In [11]:
def list2DF(l, prefix):
    columns = ['id' , 'text']
    df = pd.DataFrame(columns=columns)
    df['id'] = (range(1,len(l)+1))
    df['id'] = prefix+'_'+df['id'].astype(str)
    df['text'] = pd.Series(l)
    return df

In [24]:
broadNlpInput = list2DF(broad_scale, 'broad')
mediumNlpInput = list2DF(medium, 'medium')
localNlpInput = list2DF(local, 'local')
localNlpInput.head(20)

          id                                     text
0    local_1                            Pacific Ocean
1    local_2                               ENVO:feces
2    local_3                         arboreal habitat
3    local_4                                   spring
4    local_5               wastewater treatment plant
5    local_6                                     soil
6    local_7        biotic mesoscopic physical object
7    local_8                                Grassland
8    local_9                       Freshwater Habitat
9   local_10                                   Tundra
10  local_11                    anthropogenic habitat
11  local_12            Root soil interface of potato
12  local_13                                  missing
13  local_14                 human-associated habitat
14  local_15                                     None
15  local_16                                sea beach
16  local_17                       freshwater habitat
17  local_18  human-associated habitat; ENVO:00009003
18  local_19                                     lake
19  local_20                                  aquifer

In [13]:
nlpInput =pd.concat([broadNlpInput, mediumNlpInput, localNlpInput])
nlpInput.to_csv(os.path.join(inputDir, outFile), sep='\t', index=None)

In [17]:
%%time
runner.json2tsv(input=os.path.join(inputDir, 'envo.json'),output=os.path.join(termlistFolder, 'envo'))
runner.prepare_termlist(input=os.path.join(termlistFolder, 'envo_nodes.tsv'), output=os.path.join(termlistFolder, 'envo_termlist.tsv'))
runner.run_oger(settings=settingsFile)

[KGX][cli_utils.py][    transform_source] INFO: Processing source 'envo.json'
[KGX][json_transformer.py][               parse] INFO: Parsing ../../nlp/data/input/envo.json
[KGX][json_transformer.py][          load_nodes] INFO: Loading 6405 nodes into an instance of BaseGraph
[KGX][json_transformer.py][          load_edges] INFO: Loading 9648 edges into an instance of BaseGraph
CPU times: user 4min 26s, sys: 2.36 s, total: 4min 28s
Wall time: 4min 28s

In [18]:
ogerOutput = pd.read_csv(os.path.join(outputDir, 'runNER_Output.tsv'), sep='\t', low_memory=False)
ogerOutput = ogerOutput.drop_duplicates()
ogerOutput.head()

,DOCUMENT ID,TYPE,START POSITION,END POSITION,MATCHED TERM,PREFERRED FORM,ENTITY ID,ZONE,SENTENCE ID,ORIGIN,UMLS CUI,SENTENCE
0,broad_2,biolink:AnatomicalEntity,5,10,feces,feces,UBERON:0001988,NaN,S1,envo.json,CUI-less,ENVO:feces
1,broad_4,biolink:OntologyClass,0,3,hot,increased temperature,PATO:0001305_SYNONYM,NaN,S1,envo.json,CUI-less,hot spring
2,broad_4,biolink:OntologyClass,0,10,hot spring,hot spring,ENVO:00000051,NaN,S1,envo.json,CUI-less,hot spring
3,broad_4,biolink:OntologyClass,4,10,spring,hot spring,ENVO:00000051_SYNONYM,NaN,S1,envo.json,CUI-less,hot spring
4,broad_4,biolink:OntologyClass,4,10,spring,spring,ENVO:00000027,NaN,S1,envo.json,CUI-less,hot spring

In [19]:
termEntityId = ogerOutput[['DOCUMENT ID', 'MATCHED TERM', 'PREFERRED FORM', 'ENTITY ID']]
termEntityId = termEntityId.drop_duplicates()
termEntityId.head()

  DOCUMENT ID MATCHED TERM         PREFERRED FORM              ENTITY ID
0     broad_2        feces                  feces         UBERON:0001988
1     broad_4          hot  increased temperature   PATO:0001305_SYNONYM
2     broad_4   hot spring             hot spring          ENVO:00000051
3     broad_4       spring             hot spring  ENVO:00000051_SYNONYM
4     broad_4       spring                 spring          ENVO:00000027

In [20]:
termEntityId.to_csv(os.path.join(outputDir, 'termEntityId.tsv'), sep='\t', index=None)

In [22]:
mergedDF = localNlpInput.merge(termEntityId, how='left', left_on='id', right_on='DOCUMENT ID')
mergedDF.head()

,id,text,DOCUMENT ID,MATCHED TERM,PREFERRED FORM,ENTITY ID
0,local_1,Pacific Ocean,local_1,Ocean,ocean,ENVO:00000015
1,local_2,ENVO:feces,local_2,feces,feces,UBERON:0001988
2,local_3,arboreal habitat,local_3,habitat,habitat,ENVO:01000739
3,local_4,spring,local_4,spring,hot spring,ENVO:00000051_SYNONYM
4,local_4,spring,local_4,spring,spring,ENVO:00000027

In [23]:
mergedDF.to_csv(os.path.join(outputDir, 'mergedDF.tsv'), sep='\t', index=None)