In [1]:
%reset -f

In [49]:
import pandas as pd

In [50]:
outputDir = '../../nlp/data/nlp/output/'
outFile = 'nlpGOLDOutput.tsv'
inputDir = '../../nlp/data/nlp/input/'
inFile = 'biosamples-expanded.tsv'
#cols = ['BiosampleId', 'Biolink', 'BeginTerm', 'EndTerm', 'TokenizedTerm', 'PreferredTerm', 'CURIE', 'NaN1', 'S-Type', 'NaN2', 'UMLS_CUI']
ogerOutput = pd.read_csv(outputDir+outFile, sep='\t' )
ogerOutput = ogerOutput.drop(['BeginTerm', 'EndTerm'], axis = 1)
ogerOutput = ogerOutput.drop_duplicates()
ogerOutput.head()

,Study_BiosampleId,category,TokenizedTerm,PreferredTerm,CURIE
0,gold:Gb0101224,biolink:OntologyClass,Coal,coal,ENVO:02000091
1,gold:Gb0101224,biolink:OntologyClass,Coal Mine,coal mine,ENVO:00002169
4,gold:Gb0101224,biolink:ChemicalSubstance,water,water,CHEBI:15377
5,gold:Gb0101224,biolink:OntologyClass,water,liquid water,ENVO:00002006
6,gold:Gb0101225,biolink:OntologyClass,Coal,coal,ENVO:02000091

In [51]:
goldInput = pd.read_csv(inputDir+inFile, sep='\t', low_memory=False, usecols=['id', 'env_broad_scale', 'env_local_scale', 'env_medium'] )
goldInput.head()

               id env_broad_scale env_local_scale     env_medium
0  gold:Gb0101224   ENVO:00002030   ENVO:00002169  ENVO:00005792
1  gold:Gb0101225   ENVO:00002030   ENVO:00002169  ENVO:00005792
2  gold:Gb0101226   ENVO:00002030   ENVO:00002169  ENVO:00005792
3  gold:Gb0101227   ENVO:00002030   ENVO:00002169  ENVO:00005792
4  gold:Gb0101253   ENVO:00000446   ENVO:00002185  ENVO:00002985

In [52]:
inputOutputJoin = goldInput.merge(ogerOutput, left_on='id', right_on='Study_BiosampleId', how='left' )

In [53]:
inputOutputJoin = inputOutputJoin.drop(['Study_BiosampleId'], axis=1)
#inputOutputJoin = inputOutputJoin.drop_duplicates()
inputOutputJoin.head()

,id,env_broad_scale,env_local_scale,env_medium,category,TokenizedTerm,PreferredTerm,CURIE
0,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal,coal,ENVO:02000091
1,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal Mine,coal mine,ENVO:00002169
2,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:ChemicalSubstance,water,water,CHEBI:15377
3,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,water,liquid water,ENVO:00002006
4,gold:Gb0101225,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal,coal,ENVO:02000091

In [54]:
inputOutputJoin.to_csv(outputDir+'inputOutputJoined.tsv', sep='\t', index=None)

In [55]:
filteredMatch = inputOutputJoin.query('CURIE == env_broad_scale' and \
                                      'CURIE == env_local_scale' and \
                                      'CURIE == env_medium')

#filteredMatch = filteredMatch.drop_duplicates()

In [56]:
filteredMatch.head()

,id,env_broad_scale,env_local_scale,env_medium,category,TokenizedTerm,PreferredTerm,CURIE
18,gold:Gb0101253,ENVO:00000446,ENVO:00002185,ENVO:00002985,biolink:OntologyClass,oil,oil,ENVO:00002985
25,gold:Gb0101254,ENVO:00000446,ENVO:00002185,ENVO:00002985,biolink:OntologyClass,oil,oil,ENVO:00002985
1453,gold:Gb0102398,ENVO:00000447,ENVO:00000208,ENVO:03000033,biolink:OntologyClass,marine sediment,marine sediment,ENVO:03000033
1458,gold:Gb0102399,ENVO:00000447,ENVO:00000208,ENVO:03000033,biolink:OntologyClass,marine sediment,marine sediment,ENVO:03000033
1463,gold:Gb0102400,ENVO:00000447,ENVO:00000208,ENVO:03000033,biolink:OntologyClass,marine sediment,marine sediment,ENVO:03000033

In [57]:
filteredMatch.to_csv(outputDir+'filteredMatch.tsv', sep='\t', index=None)

In [58]:
len(inputOutputJoin)

197723

In [59]:
# env_{local,medium,broad}_matched
inputOutputJoin['env_broad_matched'] = inputOutputJoin['CURIE'] == inputOutputJoin['env_broad_scale']
inputOutputJoin['env_local_matched'] = inputOutputJoin['CURIE'] == inputOutputJoin['env_local_scale']
inputOutputJoin['env_medium_matched'] = inputOutputJoin['CURIE'] == inputOutputJoin['env_medium']
inputOutputJoin['false_positives'] = (inputOutputJoin.iloc[:,-3:]==False).all(True)

inputOutputJoin.head()

,id,env_broad_scale,env_local_scale,env_medium,category,TokenizedTerm,PreferredTerm,CURIE,env_broad_matched,env_local_matched,env_medium_matched,false_positives
0,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal,coal,ENVO:02000091,False,False,False,True
1,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal Mine,coal mine,ENVO:00002169,False,True,False,False
2,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:ChemicalSubstance,water,water,CHEBI:15377,False,False,False,True
3,gold:Gb0101224,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,water,liquid water,ENVO:00002006,False,False,False,True
4,gold:Gb0101225,ENVO:00002030,ENVO:00002169,ENVO:00005792,biolink:OntologyClass,Coal,coal,ENVO:02000091,False,False,False,True

In [60]:
grpList = ['id', 'env_broad_scale', 'env_local_scale', 'env_medium', 'category', 'TokenizedTerm', 'PreferredTerm', 'CURIE']

collapsedIO  = inputOutputJoin.groupby(grpList).any()

In [61]:
collapsedIO.head()

                                                                                                                              env_broad_matched  \
id             env_broad_scale env_local_scale env_medium    category              TokenizedTerm PreferredTerm CURIE
gold:Gb0050971 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False
                                                                                   ecosystem     ecosystem     ENVO:01001110              False
gold:Gb0050972 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False
                                                                                   ecosystem     ecosystem     ENVO:01001110              False
gold:Gb0050973 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False

                                                                                                                              env_local_matched  \
id             env_broad_scale env_local_scale env_medium    category              TokenizedTerm PreferredTerm CURIE
gold:Gb0050971 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False
                                                                                   ecosystem     ecosystem     ENVO:01001110              False
gold:Gb0050972 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False
                                                                                   ecosystem     ecosystem     ENVO:01001110              False
gold:Gb0050973 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998              False

                                                                                                                              env_medium_matched  \
id             env_broad_scale env_local_scale env_medium    category              TokenizedTerm PreferredTerm CURIE
gold:Gb0050971 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998                True
                                                                                   ecosystem     ecosystem     ENVO:01001110               False
gold:Gb0050972 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998                True
                                                                                   ecosystem     ecosystem     ENVO:01001110               False
gold:Gb0050973 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998                True

                                                                                                                              false_positives
id             env_broad_scale env_local_scale env_medium    category              TokenizedTerm PreferredTerm CURIE
gold:Gb0050971 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998            False
                                                                                   ecosystem     ecosystem     ENVO:01001110             True
gold:Gb0050972 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998            False
                                                                                   ecosystem     ecosystem     ENVO:01001110             True
gold:Gb0050973 ENVO:00000446   ENVO:01001785   ENVO:00001998 biolink:OntologyClass Soil          soil          ENVO:00001998            False

In [62]:
collapsedIO.to_csv(outputDir+'inputOutputComparison.tsv', sep='\t')

In [63]:
len(collapsedIO)

169263

In [64]:
newDf = pd.read_csv(outputDir+'inputOutputComparison.tsv', sep='\t', low_memory=False)
newDf.head()

,id,env_broad_scale,env_local_scale,env_medium,category,TokenizedTerm,PreferredTerm,CURIE,env_broad_matched,env_local_matched,env_medium_matched,false_positives
0,gold:Gb0050971,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,Soil,soil,ENVO:00001998,False,False,True,False
1,gold:Gb0050971,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True
2,gold:Gb0050972,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,Soil,soil,ENVO:00001998,False,False,True,False
3,gold:Gb0050972,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True
4,gold:Gb0050973,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,Soil,soil,ENVO:00001998,False,False,True,False

In [65]:
falsePosSubset = newDf[['id', 'CURIE', 'false_positives']]
falsePosSubset = falsePosSubset[falsePosSubset['false_positives'] == True]

In [66]:
falsePosSubset.head()

               id          CURIE  false_positives
1  gold:Gb0050971  ENVO:01001110             True
3  gold:Gb0050972  ENVO:01001110             True
5  gold:Gb0050973  ENVO:01001110             True
7  gold:Gb0050974  ENVO:01001110             True
8  gold:Gb0050975    CHEBI:37527             True

In [67]:
len(falsePosSubset)

146328

In [68]:
consolidatedFalseCURIEs = falsePosSubset.groupby(['id']).agg({'CURIE': lambda x: ','.join(x)}).rename(columns={'CURIE':'falsePositiveCURIEs'})
consolidatedFalseCURIEs.head()

                                              falsePositiveCURIEs
id
gold:Gb0050971                                      ENVO:01001110
gold:Gb0050972                                      ENVO:01001110
gold:Gb0050973                                      ENVO:01001110
gold:Gb0050974                                      ENVO:01001110
gold:Gb0050975  CHEBI:37527,ENVO:00001996,ENVO:00000083,ENVO:0...

In [45]:
consolidatedFalseCURIEs.to_csv(outputDir+'falsePositivesGroupedById.tsv', sep='\t')

In [46]:
falsePositives = pd.read_csv(outputDir+'falsePositivesGroupedById.tsv', sep='\t', low_memory=False)
falsePositives['false_positives'] = True
falsePositives.head()

,id,falsePositiveCURIEs,false_positives
0,gold:Gb0050971,ENVO:01001110,True
1,gold:Gb0050972,ENVO:01001110,True
2,gold:Gb0050973,ENVO:01001110,True
3,gold:Gb0050974,ENVO:01001110,True
4,gold:Gb0050975,"CHEBI:37527,ENVO:00001996,ENVO:00000083,ENVO:0...",True

In [47]:
finalDF = newDf.merge(falsePositives, on=['id', 'false_positives'],how='left')

In [48]:
finalDF.to_csv(outputDir+'finalOutput.tsv', sep='\t', index=None)

In [70]:
onlyFalsePosivitesDF = newDf[newDf['false_positives'] == True].merge(falsePositives, on='id',how='left')
onlyFalsePosivitesDF = onlyFalsePosivitesDF.drop_duplicates()
onlyFalsePosivitesDF.head()

,id,env_broad_scale,env_local_scale,env_medium,category,TokenizedTerm,PreferredTerm,CURIE,env_broad_matched,env_local_matched,env_medium_matched,false_positives_x,falsePositiveCURIEs,false_positives_y
0,gold:Gb0050971,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True,ENVO:01001110,True
1,gold:Gb0050972,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True,ENVO:01001110,True
2,gold:Gb0050973,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True,ENVO:01001110,True
3,gold:Gb0050974,ENVO:00000446,ENVO:01001785,ENVO:00001998,biolink:OntologyClass,ecosystem,ecosystem,ENVO:01001110,False,False,False,True,ENVO:01001110,True
4,gold:Gb0050975,ENVO:00002030,ENVO:00001997,ENVO:00002034,biolink:ChemicalSubstance,Acid,acid,CHEBI:37527,False,False,False,True,"CHEBI:37527,ENVO:00001996,ENVO:00000083,ENVO:0...",True

In [71]:
onlyFalsePosivitesDF.to_csv(outputDir+'onlyFalsePositivesOutput.tsv', sep='\t', index=None)